image: node:8

services:
  - mongo:3.6

before_script:
  - npm install

stages:
  - test
# - coverage

job_test:
  stage: test
  script:
    - npm test
  only:
    - master
    - develop

# sendcoverage:
#   stage: coverage
#   script:
#     - npm run coverage
#   only:
#     - master
#     - develop