dist: trusty
language: node_js
node_js:
    - "8"
# services:
#   - mongodb
addons:
    apt:
        sources:
            - mongodb-upstart
            - mongodb-3.6-trusty
        packages:
            - mongodb-org-server
            - mongodb-org-shell
branches:
    only:
        - master
        - develop
after_success: npm run coverage